name: Ping Domain Cron
on:
  workflow_dispatch:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping target domain
        run: curl -I https://support-bookly.onrender.com/
