name: Ping Domain Cron
on:
  workflow_dispatch:
  schedule:
    - cron: '5,17,29,41,53 * * * *' # Runs every 12 minutes, away from the top of the hour
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping target domain
        run: curl -I https://support-bookly.onrender.com/
